from PyQt6 import QtCore, QtGui, QtWidgets
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 500)
        MainWindow.setMinimumSize(QtCore.QSize(400, 500))
        MainWindow.setMaximumSize(QtCore.QSize(400, 500))
        MainWindow.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: #4E6E81;\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(parent=self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.splitter.setObjectName("splitter")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.splitter)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 75))
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 75))
        self.lineEdit.setStyleSheet("border: 1px solid rgb(46, 56, 64);\n"
"background-color: #F9DBBB;\n"
"font-weight: 600;\n"
"font-size: 25px;\n"
"padding-right: 8px;")
        self.lineEdit.setCursorPosition(0)
        self.lineEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit.setPlaceholderText(" 0")
        self.lineEdit.setObjectName("lineEdit")
        self.widget = QtWidgets.QWidget(parent=self.splitter)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Button_mult = QtWidgets.QPushButton(parent=self.widget)
        self.Button_mult.setMinimumSize(QtCore.QSize(50, 50))
        self.Button_mult.setMaximumSize(QtCore.QSize(50, 50))
        self.Button_mult.setAutoFillBackground(False)
        self.Button_mult.setStyleSheet("border-radius: 12px;background-color: #F9DBBB;\n"
"border: 1px solid rgb(46, 56, 64);")
        self.Button_mult.setObjectName("Button_mult")
        self.gridLayout.addWidget(self.Button_mult, 0, 2, 1, 1)
        self.Button_minus = QtWidgets.QPushButton(parent=self.widget)
        self.Button_minus.setMinimumSize(QtCore.QSize(50, 50))
        self.Button_minus.setMaximumSize(QtCore.QSize(50, 50))
        self.Button_minus.setAutoFillBackground(False)
        self.Button_minus.setStyleSheet("border-radius: 12px;background-color: #F9DBBB;\n"
"border: 1px solid rgb(46, 56, 64);")
        self.Button_minus.setObjectName("Button_minus")
        self.gridLayout.addWidget(self.Button_minus, 0, 3, 1, 1)
        self.Button_9 = QtWidgets.QPushButton(parent=self.widget)
        self.Button_9.setMinimumSize(QtCore.QSize(50, 50))
        self.Button_9.setMaximumSize(QtCore.QSize(50, 50))
        self.Button_9.setAutoFillBackground(False)
        self.Button_9.setStyleSheet("border-radius: 12px;background-color: #F9DBBB;\n"
"border: 1px solid rgb(46, 56, 64);")
        self.Button_9.setObjectName("Button_9")
        self.gridLayout.addWidget(self.Button_9, 1, 2, 1, 1)
        self.Button_7 = QtWidgets.QPushButton(parent=self.widget)
        self.Button_7.setMinimumSize(QtCore.QSize(50, 50))
        self.Button_7.setMaximumSize(QtCore.QSize(50, 50))
        self.Button_7.setAutoFillBackground(False)
        self.Button_7.setStyleSheet("border-radius: 12px;background-color: #F9DBBB;\n"
"border: 1px solid rgb(46, 56, 64);")
        self.Button_7.setObjectName("Button_7")
        self.gridLayout.addWidget(self.Button_7, 1, 0, 1, 1)
        self.Button_8 = QtWidgets.QPushButton(parent=self.widget)
        self.Button_8.setMinimumSize(QtCore.QSize(50, 50))
        self.Button_8.setMaximumSize(QtCore.QSize(5, 50))
        self.Button_8.setAutoFillBackground(False)
        self.Button_8.setStyleSheet("border-radius: 12px;background-color: #F9DBBB;\n"
"border: 1px solid rgb(46, 56, 64);")
        self.Button_8.setObjectName("Button_8")
        self.gridLayout.addWidget(self.Button_8, 1, 1, 1, 1)
        self.Button_2 = QtWidgets.QPushButton(parent=self.widget)
        self.Button_2.setMinimumSize(QtCore.QSize(50, 50))
        self.Button_2.setMaximumSize(QtCore.QSize(50, 50))
        self.Button_2.setAutoFillBackground(False)
        self.Button_2.setStyleSheet("border-radius: 12px;background-color: #F9DBBB;\n"
"border: 1px solid rgb(46, 56, 64);")
        self.Button_2.setObjectName("Button_2")
        self.gridLayout.addWidget(self.Button_2, 3, 1, 1, 1)
        self.Button_1 = QtWidgets.QPushButton(parent=self.widget)
        self.Button_1.setMinimumSize(QtCore.QSize(50, 50))
        self.Button_1.setMaximumSize(QtCore.QSize(50, 50))
        self.Button_1.setAutoFillBackground(False)
        self.Button_1.setStyleSheet("border-radius: 12px;background-color: #F9DBBB;\n"
"border: 1px solid rgb(46, 56, 64);")
        self.Button_1.setObjectName("Button_1")
        self.gridLayout.addWidget(self.Button_1, 3, 0, 1, 1)
        self.Button_clear = QtWidgets.QPushButton(parent=self.widget)
        self.Button_clear.setMinimumSize(QtCore.QSize(50, 50))
        self.Button_clear.setMaximumSize(QtCore.QSize(50, 50))
        self.Button_clear.setAutoFillBackground(False)
        self.Button_clear.setStyleSheet("border-radius: 12px;background-color: #F9DBBB;\n"
"border: 1px solid rgb(46, 56, 64);\n"
"color: rgb(255, 3, 3);")
        self.Button_clear.setObjectName("Button_clear")
        self.gridLayout.addWidget(self.Button_clear, 0, 0, 1, 1)
        self.Button_decrise = QtWidgets.QPushButton(parent=self.widget)
        self.Button_decrise.setMinimumSize(QtCore.QSize(50, 50))
        self.Button_decrise.setMaximumSize(QtCore.QSize(50, 50))
        self.Button_decrise.setAutoFillBackground(False)
        self.Button_decrise.setStyleSheet("border-radius: 12px;background-color: #F9DBBB;\n"
"border: 1px solid rgb(46, 56, 64);")
        self.Button_decrise.setObjectName("Button_decrise")
        self.gridLayout.addWidget(self.Button_decrise, 0, 1, 1, 1)
        self.Button_3 = QtWidgets.QPushButton(parent=self.widget)
        self.Button_3.setMinimumSize(QtCore.QSize(50, 50))
        self.Button_3.setMaximumSize(QtCore.QSize(50, 50))
        self.Button_3.setAutoFillBackground(False)
        self.Button_3.setStyleSheet("border-radius: 12px;background-color: #F9DBBB;\n"
"border: 1px solid rgb(46, 56, 64);")
        self.Button_3.setObjectName("Button_3")
        self.gridLayout.addWidget(self.Button_3, 3, 2, 1, 1)
        self.Button_plus = QtWidgets.QPushButton(parent=self.widget)
        self.Button_plus.setMinimumSize(QtCore.QSize(50, 50))
        self.Button_plus.setMaximumSize(QtCore.QSize(50, 50))
        self.Button_plus.setAutoFillBackground(False)
        self.Button_plus.setStyleSheet("border-radius: 12px;background-color: #F9DBBB;\n"
"border: 1px solid rgb(46, 56, 64);")
        self.Button_plus.setObjectName("Button_plus")
        self.gridLayout.addWidget(self.Button_plus, 1, 3, 1, 1)
        self.Button_4 = QtWidgets.QPushButton(parent=self.widget)
        self.Button_4.setMinimumSize(QtCore.QSize(50, 50))
        self.Button_4.setMaximumSize(QtCore.QSize(50, 50))
        self.Button_4.setAutoFillBackground(False)
        self.Button_4.setStyleSheet("border-radius: 12px;background-color: #F9DBBB;\n"
"border: 1px solid rgb(46, 56, 64);")
        self.Button_4.setObjectName("Button_4")
        self.gridLayout.addWidget(self.Button_4, 2, 0, 1, 1)
        self.Button_5 = QtWidgets.QPushButton(parent=self.widget)
        self.Button_5.setMinimumSize(QtCore.QSize(50, 50))
        self.Button_5.setMaximumSize(QtCore.QSize(50, 50))
        self.Button_5.setAutoFillBackground(False)
        self.Button_5.setStyleSheet("border-radius: 12px;background-color: #F9DBBB;\n"
"border: 1px solid rgb(46, 56, 64);")
        self.Button_5.setObjectName("Button_5")
        self.gridLayout.addWidget(self.Button_5, 2, 1, 1, 1)
        self.Button_6 = QtWidgets.QPushButton(parent=self.widget)
        self.Button_6.setMinimumSize(QtCore.QSize(50, 50))
        self.Button_6.setMaximumSize(QtCore.QSize(50, 50))
        self.Button_6.setAutoFillBackground(False)
        self.Button_6.setStyleSheet("border-radius: 12px;background-color: #F9DBBB;\n"
"border: 1px solid rgb(46, 56, 64);")
        self.Button_6.setObjectName("Button_6")
        self.gridLayout.addWidget(self.Button_6, 2, 2, 1, 1)
        self.Button_equal = QtWidgets.QPushButton(parent=self.widget)
        self.Button_equal.setMinimumSize(QtCore.QSize(50, 75))
        self.Button_equal.setMaximumSize(QtCore.QSize(50, 100))
        self.Button_equal.setAutoFillBackground(False)
        self.Button_equal.setStyleSheet("border-radius: 12px;background-color: #F9DBBB;\n"
"border: 1px solid rgb(46, 56, 64);\n"
"color: rgb(255, 3, 3);")
        self.Button_equal.setObjectName("Button_equal")
        self.gridLayout.addWidget(self.Button_equal, 2, 3, 2, 1)
        self.verticalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.Button_1.clicked.connect(lambda:self.to_line_text('1'))
        self.Button_2.clicked.connect(lambda:self.to_line_text('2'))
        self.Button_3.clicked.connect(lambda:self.to_line_text('3'))
        self.Button_4.clicked.connect(lambda:self.to_line_text('4'))
        self.Button_5.clicked.connect(lambda:self.to_line_text('5'))
        self.Button_6.clicked.connect(lambda:self.to_line_text('6'))
        self.Button_7.clicked.connect(lambda:self.to_line_text('7'))
        self.Button_8.clicked.connect(lambda:self.to_line_text('8'))
        self.Button_9.clicked.connect(lambda:self.to_line_text('9'))
        self.Button_equal.clicked.connect(lambda x:self.to_line_text('='))
        self.Button_plus.clicked.connect(lambda:self.to_line_text('+'))
        self.Button_minus.clicked.connect(lambda:self.to_line_text('-'))
        self.Button_decrise.clicked.connect(lambda:self.to_line_text('/'))
        self.Button_mult.clicked.connect(lambda:self.to_line_text('*'))
        self.Button_clear.clicked.connect(lambda:self.to_line_text('CE'))
        
    def to_line_text(self, txt:str):
        if txt == '=':
            print("equal")
            amal = self.lineEdit.text()
            ans = eval(amal)
            self.lineEdit.setText(str(ans))

        elif txt != 'CE':
            self.lineEdit.setText(self.lineEdit.text()+txt)    
        else:
            self.lineEdit.clear()    
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button_mult.setText(_translate("MainWindow", "*"))
        self.Button_minus.setText(_translate("MainWindow", "-"))
        self.Button_9.setText(_translate("MainWindow", "9"))
        self.Button_7.setText(_translate("MainWindow", "7"))
        self.Button_8.setText(_translate("MainWindow", "8"))
        self.Button_2.setText(_translate("MainWindow", "2"))
        self.Button_1.setText(_translate("MainWindow", "1"))
        self.Button_clear.setText(_translate("MainWindow", "CA"))
        self.Button_decrise.setText(_translate("MainWindow", "/"))
        self.Button_3.setText(_translate("MainWindow", "3"))
        self.Button_plus.setText(_translate("MainWindow", "+"))
        self.Button_4.setText(_translate("MainWindow", "4"))
        self.Button_5.setText(_translate("MainWindow", "5"))
        self.Button_6.setText(_translate("MainWindow", "6"))
        self.Button_equal.setText(_translate("MainWindow", "="))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
